version: "3"
services:
  my5grantester:
    build:
      context: ./
    container_name: my5grantester
    privileged: true
    command: ./app ${TEST_PARAMETERS}
    volumes:
      - ./config/tester.yaml:/workspace/my5G-RANTester/config/config.yml
    cap_add:
      - NET_ADMIN
    networks:
      default:
        aliases:
          - tester.free5gc.org

  iperf:
    image: mlabbe/iperf:latest
    container_name: iperf
    ports:
      - 5001:5001
    command: -s
    networks:
      default:
        aliases:
          - iperf.free5gc.org

networks:
  default:
    external:
      name: "free5gc-compose_default"
